### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by stefanstranger** [stefanstranger/pswiniot#2]
When trying to call a web request using a body (json) I get the following error.
[192.168.1.34]: PS C:> Invoke-WinIoTWebRequest -Uri $url -Method Post -Body $Body -ContentType application/json
Unable to find type [Encoding].
At C:\PSWinIoT.psm1:202 char:13
-             $request.Content = `
-             ~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (Encoding:TypeName) [], RuntimeException
  - FullyQualifiedErrorId : TypeNotFound

[
  {
    "code": "ParameterIsMissing",
    "message": "'request' is required."
  }
]

[192.168.1.34]: PS C:> $body
{
     "ApplicationId": "1234566",
    "Password": "verysecret",
    "Username": "sstranger" 
}

**Comment by sqlchow** [comment]
Let me take a look at the issue. It looks like an issue with line 203. [System.Text.Encoding] instead of [Encoding].

**Comment by sqlchow** [comment]
@stefanstranger I think, I fixed the encoding issue. Please check.

**Comment by stefanstranger** [comment]
Solved the issue.
